{ stdenv
, pkgs
, enableCriu
, enableSystemd
, libcap
, libseccomp
, libsystemd
, yajl
, criu
}:
with pkgs; stdenv.mkDerivation {
  name = "crun";
  src = ./..;
  vendorSha256 = null;
  doCheck = false;
  enableParallelBuilding = true;
  outputs = [ "out" ];
  nativeBuildInputs = with buildPackages; [
    autoreconfHook
    autoPatchelfHook
    bash
    git
    pkg-config
    python3
    which
  ];
  buildInputs =
    (if stdenv.hostPlatform.isMusl then [
      argp-standalone
    ] else [
      glibc
      glibc.static
    ]) ++ [
      libcap
      libseccomp
      libsystemd
      yajl
    ] ++ lib.optionals enableCriu [ criu ];
  configureFlags = [ "--enable-static" ] ++ lib.optional (!enableSystemd) [ "--disable-systemd" ];
  prePatch = let
    staticLibs =
      lib.optional enableCriu "${criu}/lib/libcriu.a"
      ++ (if stdenv.hostPlatform.isMusl
          then map (l: "${musl}/lib/${l}") [ "libc.a" "libpthread.a" "librt.a" ]
          else map (l: "${glibc.static}/lib/${l}") [ "libc.a" "libpthread.a" "librt.a" ])
      ++ [
        "${lib.getLib libcap}/lib/libcap.a"
        "${lib.getLib libseccomp}/lib/libseccomp.a"
      ]
      ++ lib.optional enableSystemd "${lib.getLib libsystemd}/lib/libsystemd.a"
      ++ [ "${yajl}/lib/libyajl.a" ];
  in ''
    export CFLAGS='-static -pthread -DSTATIC'
    export LDFLAGS='-s -w -static-libgcc -static'
    export EXTRA_LDFLAGS='-s -w -linkmode external -extldflags "-static -lm"'
    export CRUN_LDFLAGS='-all-static'
    export LIBS='${lib.concatStringsSep " " staticLibs}'
  '';
  buildPhase = ''
    patchShebangs .
    if [ -f .tarball-git-version.h ]; then
      cp .tarball-git-version.h git-version.h
    elif [ -f .git ]; then
      version=$(git rev-parse HEAD)
      printf '/* autogenerated.  */\n#ifndef GIT_VERSION\n# define GIT_VERSION "%s"\n#endif\n' "$version" > git-version.h
    else
      printf '/* autogenerated.  */\n#ifndef GIT_VERSION\n# define GIT_VERSION "unknown"\n#endif\n' > git-version.h
    fi
    make -C libocispec libocispec.la
    make crun
  '';
  installPhase = ''
    install -Dm755 crun $out/bin/crun
  '';
}
