#!/bin/bash
# Run a single CI test case.  Called from .github/workflows/test.yaml with the
# name of the test (i.e. the value of the "test" matrix entry) as its only
# argument.  Keeping this out of the workflow file means shellcheck and shfmt
# get to look at it.

set -e

test_name=${1:?usage: $0 <test-name>}

# Wrap a command in a collapsible log group, so that the build noise
# and the individual test runs can be told apart.  The group is closed
# on failure as well, so that anything printed afterwards -- the test
# suite log, most of all -- stays outside of it and thus visible.
group() {
    local name=$1 rc=0
    shift
    echo "::group::$name"
    "$@" || rc=$?
    echo "::endgroup::"
    return $rc
}

# Print the test suite log and fail.  Called when a "make check" fails; the
# log is what actually says which test broke and how.
dump_log() {
    cat test-suite.log
    exit 1
}

# Configure and build, with any extra configure arguments in "$@".
build() {
    group configure ./configure --enable-embedded-blake3 --enable-werror "$@"
    group build make -j "$(nproc)"
}

# Build the container image for the current test from tests/<test>/Dockerfile
# and run it with the repository bind mounted at /crun.  Any extra docker run
# arguments come from "$@".
run_container() {
    local image="crun-$test_name"

    group "docker build" sudo docker build -t "$image" "tests/$test_name"
    sudo docker run --rm -v "${PWD}":/crun "$@" "$image"
}

# The docker run arguments needed by a test that itself runs containers: it
# has to share the host cgroup namespace and see the host cgroup tree.
privileged=(--cgroupns=host --privileged -v "/sys/fs/cgroup:/sys/fs/cgroup:rw,rslave")

case "$test_name" in
disable-systemd)
    build --disable-systemd
    ;;
check)
    sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
    build --disable-dl
    # Check that autogenerated files that are in git has not changed.
    git diff --exit-code

    group "syntax check" make syntax-check
    group "tests as root" \
        sudo make check ASAN_OPTIONS=detect_leaks=false || dump_log
    group "tests as rootless" \
        make check ASAN_OPTIONS=detect_leaks=false || dump_log
    group "tests as rootless in a user namespace" \
        unshare -r make check ASAN_OPTIONS=detect_leaks=false || dump_log
    ;;
check-no-openat2)
    # Run the test suite with openat2(2) forced to fail with
    # ENOSYS, so that the safe_openat() fallback used on kernels
    # older than 5.6 is exercised.  GitHub runners always have a
    # much newer kernel, so this path is otherwise never tested.
    sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
    build --disable-dl
    # Only the root run: without CAP_SYS_ADMIN the helper has to
    # set NO_NEW_PRIVS to install its seccomp filter, and that is
    # inherited by the test containers.
    group "tests as root, openat2 blocked" \
        sudo make check-no-openat2 ASAN_OPTIONS=detect_leaks=false || dump_log
    ;;
check-systemd)
    # Run the test suite with the systemd cgroup manager.  The
    # tests know which of them are specific to one cgroup manager
    # or the other, but by default they only ever exercise the
    # cgroupfs one.
    sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
    build --disable-dl

    group "tests as root, systemd cgroup manager" \
        sudo make check-systemd ASAN_OPTIONS=detect_leaks=false || dump_log

    # The rootless run needs a systemd user session, since that
    # is what rootless crun asks to create the container scope.
    # The runner user never logs in, so nothing starts one:
    # install the session bus, then enable lingering to bring
    # user@$UID.service up, and point the run at its bus.  Ending
    # up in the right cgroup is up to the script, see the comment
    # in tests/run_rootless_systemd.sh.
    group "install dbus-user-session" sudo apt-get install -q -y dbus-user-session
    sudo loginctl enable-linger "$(id -un)"
    XDG_RUNTIME_DIR="/run/user/$(id -u)"
    DBUS_SESSION_BUS_ADDRESS="unix:path=$XDG_RUNTIME_DIR/bus"
    export XDG_RUNTIME_DIR DBUS_SESSION_BUS_ADDRESS
    for _ in $(seq 30); do
        test -S "$XDG_RUNTIME_DIR/bus" && break
        sleep 1
    done

    group "tests as rootless, systemd cgroup manager" \
        ./tests/run_rootless_systemd.sh
    ;;
podman | centos10-build)
    sudo mkdir -p /var/lib/containers /var/tmp
    run_container "${privileged[@]}" \
        -v /var/tmp:/var/tmp:rw -v /var/lib/containers:/var/lib/containers:rw
    ;;
#cri-o)
#    sudo mkdir -p /var/lib/var-crio/tmp /var/lib/tmp-crio /var/lib/var-tmp-crio
#    run_container "${privileged[@]}" --net host \
#        -v /dev/zero:/sys/module/apparmor/parameters/enabled \
#        -v /var/lib/tmp-crio:/tmp:rw -v /var/lib/var-tmp-crio:/var/tmp \
#        -v /var/lib/var-crio:/var/lib/containers:rw
#    ;;
containerd)
    sudo mkdir -p /var/lib/var-containerd
    # Not "${privileged[@]}": this one wants all of /sys, not just the
    # cgroup tree.
    run_container --cgroupns=host --privileged --net host \
        -v /tmp:/tmp:rw -v /var/lib/var-containerd:/var/lib:rw -v /sys:/sys:rw,rslave
    ;;
oci-validation | alpine-build | centos9-build)
    run_container "${privileged[@]}"
    ;;
clang-format | cppcheck)
    run_container -w /crun
    ;;
clang-check)
    run_container --privileged -w /crun
    ;;
enable-shared)
    build --enable-shared
    ;;
bindings)
    # Build the Python and Lua bindings and load each freshly
    # built module.  The bindings link against internal libcrun
    # symbols, so a build here catches API drift and missing
    # exports (e.g. libcrun_container_spec, parse_json_file)
    # before it reaches a release.
    build --enable-shared --with-python-bindings --with-lua-bindings
    export LD_LIBRARY_PATH="$PWD/.libs:$LD_LIBRARY_PATH"
    PYTHONPATH="$PWD/.libs" python3 python/test_python_bindings.py
    LUA_CPATH="$PWD/.libs/?.so;;" lua5.4 lua/test_lua_bindings.lua
    ;;
embedded-blake3)
    build
    ;;
system-blake3)
    run_container
    ;;
checkpoint-restore)
    build
    # Use check-am (not "make tests/*.trs", which always exits 0
    # regardless of the test result, and not "make check", which
    # recurses into libocispec with the TESTS override).
    group "tests as root" \
        sudo make check-am TESTS=tests/test_checkpoint_restore.py || dump_log
    ;;
fuzzing)
    run_container "${privileged[@]}" -e RUN_TIME=300
    ;;
codespell)
    group "install codespell" pip install --break-system-packages codespell==v2.4.1 # Use known version
    codespell
    ;;
wasmedge-build)
    run_container "${privileged[@]}" -v containers:/var/lib/containers:rw -w /crun
    ;;
*)
    echo "unknown test: $test_name" >&2
    exit 1
    ;;
esac
