#!/bin/bash
# Run a single CI test case.  Called from .github/workflows/test.yaml with the
# name of the test (i.e. the value of the "test" matrix entry) as its only
# argument.  Keeping this out of the workflow file means shellcheck and shfmt
# get to look at it.

set -e

test_name=${1:?usage: $0 <test-name>}

# Wrap a command in a collapsible log group, so that the build noise
# and the individual test runs can be told apart.  The group is closed
# on failure as well, so that anything printed afterwards -- the test
# suite log, most of all -- stays outside of it and thus visible.
group() {
    local name=$1 rc=0
    shift
    echo "::group::$name"
    "$@" || rc=$?
    echo "::endgroup::"
    return $rc
}

# Print the test suite log and fail.  Called when a "make check" fails; the
# log is what actually says which test broke and how.
dump_log() {
    cat test-suite.log
    exit 1
}

case "$test_name" in
disable-systemd)
    group configure ./configure --enable-embedded-blake3 --disable-systemd --enable-werror
    group build make -j "$(nproc)"
    ;;
check)
    sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
    group configure ./configure --enable-embedded-blake3 --disable-dl --enable-werror
    group build make -j "$(nproc)"
    # Check that autogenerated files that are in git has not changed.
    git diff --exit-code

    group "syntax check" make syntax-check
    group "tests as root" \
        sudo make check ASAN_OPTIONS=detect_leaks=false || dump_log
    group "tests as rootless" \
        make check ASAN_OPTIONS=detect_leaks=false || dump_log
    group "tests as rootless in a user namespace" \
        unshare -r make check ASAN_OPTIONS=detect_leaks=false || dump_log
    ;;
check-no-openat2)
    # Run the test suite with openat2(2) forced to fail with
    # ENOSYS, so that the safe_openat() fallback used on kernels
    # older than 5.6 is exercised.  GitHub runners always have a
    # much newer kernel, so this path is otherwise never tested.
    sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
    group configure ./configure --enable-embedded-blake3 --disable-dl --enable-werror
    group build make -j "$(nproc)"
    # Only the root run: without CAP_SYS_ADMIN the helper has to
    # set NO_NEW_PRIVS to install its seccomp filter, and that is
    # inherited by the test containers.
    group "tests as root, openat2 blocked" \
        sudo make check-no-openat2 ASAN_OPTIONS=detect_leaks=false || dump_log
    ;;
check-systemd)
    # Run the test suite with the systemd cgroup manager.  The
    # tests know which of them are specific to one cgroup manager
    # or the other, but by default they only ever exercise the
    # cgroupfs one.
    sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
    group configure ./configure --enable-embedded-blake3 --disable-dl --enable-werror
    group build make -j "$(nproc)"

    group "tests as root, systemd cgroup manager" \
        sudo make check-systemd ASAN_OPTIONS=detect_leaks=false || dump_log

    # The rootless run needs a systemd user session, since that
    # is what rootless crun asks to create the container scope.
    # The runner user never logs in, so nothing starts one:
    # install the session bus, then enable lingering to bring
    # user@$UID.service up, and point the run at its bus.  Ending
    # up in the right cgroup is up to the script, see the comment
    # in tests/run_rootless_systemd.sh.
    group "install dbus-user-session" sudo apt-get install -q -y dbus-user-session
    sudo loginctl enable-linger "$(id -un)"
    XDG_RUNTIME_DIR="/run/user/$(id -u)"
    DBUS_SESSION_BUS_ADDRESS="unix:path=$XDG_RUNTIME_DIR/bus"
    export XDG_RUNTIME_DIR DBUS_SESSION_BUS_ADDRESS
    for _ in $(seq 30); do
        test -S "$XDG_RUNTIME_DIR/bus" && break
        sleep 1
    done

    group "tests as rootless, systemd cgroup manager" \
        ./tests/run_rootless_systemd.sh
    ;;
podman)
    sudo mkdir -p /var/lib/containers /var/tmp
    group "docker build" sudo docker build -t crun-podman tests/podman
    sudo docker run --cgroupns=host --privileged --rm -v /var/tmp:/var/tmp:rw -v /var/lib/containers:/var/lib/containers:rw -v /sys/fs/cgroup:/sys/fs/cgroup:rw,rslave -v "${PWD}":/crun crun-podman
    ;;
#cri-o)
#    sudo mkdir -p /var/lib/var-crio/tmp /var/lib/tmp-crio /var/lib/var-tmp-crio
#    group "docker build" sudo docker build -t crun-cri-o tests/cri-o
#    sudo docker run --cgroupns=host  --net host --privileged --rm -v /dev/zero:/sys/module/apparmor/parameters/enabled -v /var/lib/tmp-crio:/tmp:rw -v /var/lib/var-tmp-crio:/var/tmp -v /var/lib/var-crio:/var/lib/containers:rw -v /sys/fs/cgroup:/sys/fs/cgroup:rw,rslave -v "${PWD}":/crun crun-cri-o
#    ;;
containerd)
    sudo mkdir -p /var/lib/var-containerd
    group "docker build" sudo docker build -t crun-containerd tests/containerd
    sudo docker run --cgroupns=host --privileged --net host --rm -v /tmp:/tmp:rw -v /var/lib/var-containerd:/var/lib:rw -v /sys:/sys:rw,rslave -v "${PWD}":/crun crun-containerd
    ;;
oci-validation)
    group "docker build" sudo docker build -t crun-oci-validation tests/oci-validation
    sudo docker run --cgroupns=host --privileged --rm -v /sys/fs/cgroup:/sys/fs/cgroup:rw,rslave -v "${PWD}":/crun crun-oci-validation
    ;;
alpine-build)
    group "docker build" sudo docker build -t crun-alpine-build tests/alpine-build
    sudo docker run --cgroupns=host --privileged --rm -v /sys/fs/cgroup:/sys/fs/cgroup:rw,rslave -v "${PWD}":/crun crun-alpine-build
    ;;
centos9-build)
    group "docker build" sudo docker build -t crun-centos9-build tests/centos9-build
    sudo docker run --cgroupns=host --privileged --rm -v /sys/fs/cgroup:/sys/fs/cgroup:rw,rslave -v "${PWD}":/crun crun-centos9-build
    ;;
centos10-build)
    group "docker build" sudo docker build -t crun-centos10-build tests/centos10-build
    sudo docker run --cgroupns=host --privileged --rm -v /var/tmp:/var/tmp:rw -v /var/lib/containers:/var/lib/containers:rw -v /sys/fs/cgroup:/sys/fs/cgroup:rw,rslave -v "${PWD}":/crun crun-centos10-build
    ;;
clang-format)
    group "docker build" sudo docker build -t crun-clang-format tests/clang-format
    sudo docker run --rm -w /crun -v "${PWD}":/crun crun-clang-format
    ;;
clang-check)
    group "docker build" sudo docker build -t crun-clang-check tests/clang-check
    sudo docker run --privileged --rm -w /crun -v "${PWD}":/crun crun-clang-check
    ;;
cppcheck)
    group "docker build" sudo docker build -t crun-cppcheck tests/cppcheck
    sudo docker run --rm -w /crun -v "${PWD}":/crun crun-cppcheck
    ;;
enable-shared)
    group configure ./configure --enable-embedded-blake3 --enable-shared --enable-werror
    group build make -j "$(nproc)"
    ;;
bindings)
    # Build the Python and Lua bindings and load each freshly
    # built module.  The bindings link against internal libcrun
    # symbols, so a build here catches API drift and missing
    # exports (e.g. libcrun_container_spec, parse_json_file)
    # before it reaches a release.
    group configure ./configure --enable-embedded-blake3 --enable-shared --with-python-bindings --with-lua-bindings --enable-werror
    group build make -j "$(nproc)"
    export LD_LIBRARY_PATH="$PWD/.libs:$LD_LIBRARY_PATH"
    PYTHONPATH="$PWD/.libs" python3 python/test_python_bindings.py
    LUA_CPATH="$PWD/.libs/?.so;;" lua5.4 lua/test_lua_bindings.lua
    ;;
embedded-blake3)
    group configure ./configure --enable-embedded-blake3 --enable-werror
    group build make -j "$(nproc)"
    ;;
system-blake3)
    group "docker build" sudo docker build -t crun-system-blake3 tests/system-blake3
    sudo docker run --rm -v "${PWD}":/crun crun-system-blake3
    ;;
checkpoint-restore)
    group configure ./configure --enable-embedded-blake3 --enable-werror
    group build make -j "$(nproc)"
    # Use check-am (not "make tests/*.trs", which always exits 0
    # regardless of the test result, and not "make check", which
    # recurses into libocispec with the TESTS override).
    group "tests as root" \
        sudo make check-am TESTS=tests/test_checkpoint_restore.py || dump_log
    ;;
fuzzing)
    group "docker build" sudo docker build -t crun-fuzzing tests/fuzzing
    sudo docker run --cgroupns=host -e RUN_TIME=300 --privileged --rm -v /sys/fs/cgroup:/sys/fs/cgroup:rw,rslave -v "${PWD}":/crun crun-fuzzing
    ;;
codespell)
    group "install codespell" pip install --break-system-packages codespell==v2.4.1 # Use known version
    codespell
    ;;
wasmedge-build)
    group "docker build" sudo docker build -t wasmedge tests/wasmedge-build
    sudo docker run --privileged --cgroupns=host --rm -v containers:/var/lib/containers:rw -v /sys/fs/cgroup:/sys/fs/cgroup:rw,rslave -w /crun -v "${PWD}":/crun wasmedge
    ;;
esac
