TESTS := $(shell find . -name "test_*.py")

INIT ?= init
OCI_RUNTIME ?= /usr/bin/crun

check: $(INIT) tap-driver.sh
	OCI_RUNTIME=${OCI_RUNTIME} INIT=${INIT} ./run_all_tests.sh

tap-driver.sh:
	wget https://git.savannah.gnu.org/cgit/automake.git/plain/lib/tap-driver.sh
	chmod +x tap-driver.sh

init: init.c
	$(CC) -static $< -o $@
