.PHONY: podman_system_test_upstream
podman_system_test_upstream:
	bash ./podman-tests.sh upstream

.PHONY: podman_system_test_downstream
podman_system_test_downstream:
	bash ./podman-tests.sh downstream
